FROM ubuntu:oracular
ARG DEBIAN_FRONTEND=noninteractive
ARG GOBIN="/usr/bin"
ARG GOMODCACHE="/tmp/gomod"
ARG GOCACHE="/tmp/gocache"

RUN echo "cache buster 059a9a06-1686-4f49-9a7f-a30535886d58"
RUN apt-get update
RUN apt-get install -y software-properties-common build-essential ca-certificates curl sudo
RUN add-apt-repository -n ppa:longsleep/golang-backports
RUN add-apt-repository -n ppa:egdaemon/eg
RUN add-apt-repository -n ppa:egdaemon/duckdb

RUN echo "cache buster 059a9a06-1686-4f49-9a7f-a30535886d58"
RUN apt-get update
RUN apt-get -y install golang-1.24 eg egbootstrap duckdb podman netavark rsync vim dput devscripts dh-make dput uidmap dbus-user-session git unzip xz-utils zip libglu1-mesa clang cmake git ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
RUN sh /usr/share/eg/install/github.sh > /dev/null
RUN apt-get -y install snapd protobuf-compiler pkgconf clang-19 gh tree flatpak-builder libmpv-dev

RUN ln -s /usr/lib/go-1.24/bin/go /usr/local/bin/go

# install flutter
RUN curl -o /tmp/flutter.tar.xz https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.32.7-stable.tar.xz
RUN tar -xf /tmp/flutter.tar.xz -C /opt/
RUN ln -s /opt/flutter/bin/flutter /usr/local/bin/flutter
RUN ln -s /opt/flutter/bin/dart /usr/local/bin/dart
RUN protoc --version
RUN chown -R egd:egd /opt/flutter
RUN sudo -H -S -u egd -g egd flutter config --no-analytics
RUN sudo -H -S -u egd -g egd flutter --disable-analytics
RUN sudo -H -S -u egd -g egd dart pub global activate protoc_plugin

# install flatpak
RUN apt-get update
RUN apt-get -y install tree flatpak-builder libmpv-dev
RUN flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# install genieql and golang's protocol buffers and other dev tooling.
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install github.com/fatih/gomodifytags@latest
RUN echo "cache buster 059a9a06-1686-4f49-9a7f-a30535786d53"
RUN GOPROXY=direct go install -tags duckdb_use_lib github.com/james-lawrence/genieql/...@latest
RUN GOPROXY=direct go install github.com/egdaemon/eg/cmd/...@v0.0.0-20250806181324-a1420405d47b
RUN systemd-tmpfiles --create
RUN systemd-tmpfiles --clean