version: 2
pro: true
release:
  disable: true
  skip_upload: true

before:
  hooks:
    - go env
builds:
  # - id: retrovibed-amd64
  #   env:
  #     - FOO=BAR
  #   goos:
  #     - darwin # macOS
  #   goarch:
  #     - amd64 # Intel-based Macs
  #   main: ./shallows/cmd/retrovibed # Path to your main package
  #   binary: retrovibed # Name of the output binary
  #   tags:
  #     - duckdb_use_lib
  - id: retrovibed-arm64
    env:
      - FOO=BAR
      # - CGO_ENABLED=1
    goos:
      - darwin
    goarch:
      - arm64
    main: ./shallows/cmd/cmdmacosxtest
    binary: retrovibed
    flags:
      - -x
      - -v
    # tags:
    #   - duckdb_use_lib

app_bundles:
  - id: retrovibed # A unique ID for this app bundle
    # builds:
    #   - retrovibed-arm64 # Reference the build ID from above
    name: "Retrovibed"
    bundle: "space.retrovibe.retrovibed"
    icon: ".dist/linux/usr/share/icons/hicolor/scalable/apps/retrovibed.svg"
    # Optional: Customize Info.plist if needed
    # info_plist:
    #   NSHumanReadableCopyright: "Copyright © 2025 Your Organization. All rights reserved."
    #   LSMinimumSystemVersion: "10.15.0"

dmg:
  - # ID of the resulting image.
    #
    # Default: the project name.
    id: retrovibed

    # Filename of the image (without the extension).
    #
    # Default: '{{.ProjectName}}_{{.Arch}}'.
    # Templates: allowed.
    name: "{{.ProjectName}}.{{.Arch}}"

    # # IDs of the archives to use.
    # # Empty means all IDs.
    # ids:
    #   - foo
    #   - bar

    # Which kind of artifact to use.
    #
    # Valid options are:
    # - 'binary':    binary
    # - 'appbundle': app bundles
    #
    # Default: 'binary'
    # This feature is only available in GoReleaser Pro.
    # Since: v2.4.
    use: appbundle

    # Allows to further filter the artifacts.
    #
    # Artifacts that do not match this expression will be ignored.
    #
    # This feature is only available in GoReleaser Pro.
    # Since: v2.4.
    # Templates: allowed.
    # if: '{{ eq .Os "darwin" }}'

    # # GOAMD64 to specify which amd64 version to use if there are multiple
    # # versions from the build section.
    # #
    # # Default: v1.
    # goamd64: v1

    # # More files that will be available in the context in which the image
    # # will be built.
    # extra_files:
    #   - logo.ico
    #   - glob: ./docs/*.md
    #   - glob: ./single_file.txt
    #     # Templates: allowed.
    #     # Note that this only works if glob matches exactly 1 file.
    #     name_template: file.txt

    # Additional templated extra files to add to the DMG.
    # Those files will have their contents pass through the template engine,
    # and its results will be added to the image as it would with the
    # extra_files field above.
    #
    # This feature is only available in GoReleaser Pro.
    # Since: v2.4.
    # Templates: allowed.
    # templated_extra_files:
    #   - src: LICENSE.tpl
    #     dst: LICENSE.txt
    #     mode: 0644

    # Whether to remove the archives from the artifact list.
    # If left as false, your end release will have both the archives and the
    # dmg files.
    replace: true

    # Set the modified timestamp on the output image, typically
    # you would do this to ensure a build was reproducible. Pass an
    # empty string to skip modifying the output.
    #
    # Templates: allowed.
    mod_timestamp: "{{ .CommitTimestamp }}"
