// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: community.proto

package meta

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Community struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AccountId     string                 `protobuf:"bytes,2,opt,name=account_id,proto3" json:"account_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,5,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	Mimetype      string                 `protobuf:"bytes,6,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Domain        string                 `protobuf:"bytes,7,opt,name=domain,proto3" json:"domain,omitempty"`
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	Entropy       string                 `protobuf:"bytes,9,opt,name=entropy,proto3" json:"entropy,omitempty"`
	Bytes         uint64                 `protobuf:"varint,10,opt,name=bytes,proto3" json:"bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Community) Reset() {
	*x = Community{}
	mi := &file_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Community) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Community) ProtoMessage() {}

func (x *Community) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Community.ProtoReflect.Descriptor instead.
func (*Community) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{0}
}

func (x *Community) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Community) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Community) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Community) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Community) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *Community) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Community) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Community) GetEntropy() string {
	if x != nil {
		return x.Entropy
	}
	return ""
}

func (x *Community) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

type CommunitySearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunitySearchRequest) Reset() {
	*x = CommunitySearchRequest{}
	mi := &file_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunitySearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunitySearchRequest) ProtoMessage() {}

func (x *CommunitySearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunitySearchRequest.ProtoReflect.Descriptor instead.
func (*CommunitySearchRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{1}
}

func (x *CommunitySearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *CommunitySearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *CommunitySearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type CommunitySearchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Next          *CommunitySearchRequest `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Community            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunitySearchResponse) Reset() {
	*x = CommunitySearchResponse{}
	mi := &file_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunitySearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunitySearchResponse) ProtoMessage() {}

func (x *CommunitySearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunitySearchResponse.ProtoReflect.Descriptor instead.
func (*CommunitySearchResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{2}
}

func (x *CommunitySearchResponse) GetNext() *CommunitySearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *CommunitySearchResponse) GetItems() []*Community {
	if x != nil {
		return x.Items
	}
	return nil
}

type CommunityCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityCreateRequest) Reset() {
	*x = CommunityCreateRequest{}
	mi := &file_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCreateRequest) ProtoMessage() {}

func (x *CommunityCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCreateRequest.ProtoReflect.Descriptor instead.
func (*CommunityCreateRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{3}
}

func (x *CommunityCreateRequest) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type CommunityCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityCreateResponse) Reset() {
	*x = CommunityCreateResponse{}
	mi := &file_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityCreateResponse) ProtoMessage() {}

func (x *CommunityCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityCreateResponse.ProtoReflect.Descriptor instead.
func (*CommunityCreateResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{4}
}

func (x *CommunityCreateResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type CommunityFindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityFindRequest) Reset() {
	*x = CommunityFindRequest{}
	mi := &file_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityFindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityFindRequest) ProtoMessage() {}

func (x *CommunityFindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityFindRequest.ProtoReflect.Descriptor instead.
func (*CommunityFindRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{5}
}

type CommunityFindResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityFindResponse) Reset() {
	*x = CommunityFindResponse{}
	mi := &file_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityFindResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityFindResponse) ProtoMessage() {}

func (x *CommunityFindResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityFindResponse.ProtoReflect.Descriptor instead.
func (*CommunityFindResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{6}
}

func (x *CommunityFindResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type CommunityUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityUploadRequest) Reset() {
	*x = CommunityUploadRequest{}
	mi := &file_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityUploadRequest) ProtoMessage() {}

func (x *CommunityUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityUploadRequest.ProtoReflect.Descriptor instead.
func (*CommunityUploadRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{7}
}

func (x *CommunityUploadRequest) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type CommunityUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommunityUploadResponse) Reset() {
	*x = CommunityUploadResponse{}
	mi := &file_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommunityUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommunityUploadResponse) ProtoMessage() {}

func (x *CommunityUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommunityUploadResponse.ProtoReflect.Descriptor instead.
func (*CommunityUploadResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{8}
}

func (x *CommunityUploadResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

var File_community_proto protoreflect.FileDescriptor

const file_community_proto_rawDesc = "" +
	"\n" +
	"\x0fcommunity.proto\x12\x14retrovibed.community\"\x88\x02\n" +
	"\tCommunity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1e\n" +
	"\n" +
	"account_id\x18\x02 \x01(\tR\n" +
	"account_id\x12\x1e\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\n" +
	"created_at\x12\x1e\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\tR\n" +
	"updated_at\x12\x1a\n" +
	"\bmimetype\x18\x06 \x01(\tR\bmimetype\x12\x16\n" +
	"\x06domain\x18\a \x01(\tR\x06domain\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\x12\x18\n" +
	"\aentropy\x18\t \x01(\tR\aentropy\x12\x14\n" +
	"\x05bytes\x18\n" +
	" \x01(\x04R\x05bytesJ\x05\b\x14\x10\xe8\a\"c\n" +
	"\x16CommunitySearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limitJ\x05\b\x04\x10\xe8\a\"\x92\x01\n" +
	"\x17CommunitySearchResponse\x12@\n" +
	"\x04next\x18\x01 \x01(\v2,.retrovibed.community.CommunitySearchRequestR\x04next\x125\n" +
	"\x05items\x18\x02 \x03(\v2\x1f.retrovibed.community.CommunityR\x05items\"W\n" +
	"\x16CommunityCreateRequest\x12=\n" +
	"\tcommunity\x18\x01 \x01(\v2\x1f.retrovibed.community.CommunityR\tcommunity\"X\n" +
	"\x17CommunityCreateResponse\x12=\n" +
	"\tcommunity\x18\x01 \x01(\v2\x1f.retrovibed.community.CommunityR\tcommunity\"\x16\n" +
	"\x14CommunityFindRequest\"V\n" +
	"\x15CommunityFindResponse\x12=\n" +
	"\tcommunity\x18\x01 \x01(\v2\x1f.retrovibed.community.CommunityR\tcommunity\"W\n" +
	"\x16CommunityUploadRequest\x12=\n" +
	"\tcommunity\x18\x01 \x01(\v2\x1f.retrovibed.community.CommunityR\tcommunity\"X\n" +
	"\x17CommunityUploadResponse\x12=\n" +
	"\tcommunity\x18\x01 \x01(\v2\x1f.retrovibed.community.CommunityR\tcommunityb\x06proto3"

var (
	file_community_proto_rawDescOnce sync.Once
	file_community_proto_rawDescData []byte
)

func file_community_proto_rawDescGZIP() []byte {
	file_community_proto_rawDescOnce.Do(func() {
		file_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_proto_rawDesc), len(file_community_proto_rawDesc)))
	})
	return file_community_proto_rawDescData
}

var file_community_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_community_proto_goTypes = []any{
	(*Community)(nil),               // 0: retrovibed.community.Community
	(*CommunitySearchRequest)(nil),  // 1: retrovibed.community.CommunitySearchRequest
	(*CommunitySearchResponse)(nil), // 2: retrovibed.community.CommunitySearchResponse
	(*CommunityCreateRequest)(nil),  // 3: retrovibed.community.CommunityCreateRequest
	(*CommunityCreateResponse)(nil), // 4: retrovibed.community.CommunityCreateResponse
	(*CommunityFindRequest)(nil),    // 5: retrovibed.community.CommunityFindRequest
	(*CommunityFindResponse)(nil),   // 6: retrovibed.community.CommunityFindResponse
	(*CommunityUploadRequest)(nil),  // 7: retrovibed.community.CommunityUploadRequest
	(*CommunityUploadResponse)(nil), // 8: retrovibed.community.CommunityUploadResponse
}
var file_community_proto_depIdxs = []int32{
	1, // 0: retrovibed.community.CommunitySearchResponse.next:type_name -> retrovibed.community.CommunitySearchRequest
	0, // 1: retrovibed.community.CommunitySearchResponse.items:type_name -> retrovibed.community.Community
	0, // 2: retrovibed.community.CommunityCreateRequest.community:type_name -> retrovibed.community.Community
	0, // 3: retrovibed.community.CommunityCreateResponse.community:type_name -> retrovibed.community.Community
	0, // 4: retrovibed.community.CommunityFindResponse.community:type_name -> retrovibed.community.Community
	0, // 5: retrovibed.community.CommunityUploadRequest.community:type_name -> retrovibed.community.Community
	0, // 6: retrovibed.community.CommunityUploadResponse.community:type_name -> retrovibed.community.Community
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_community_proto_init() }
func file_community_proto_init() {
	if File_community_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_proto_rawDesc), len(file_community_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_community_proto_goTypes,
		DependencyIndexes: file_community_proto_depIdxs,
		MessageInfos:      file_community_proto_msgTypes,
	}.Build()
	File_community_proto = out.File
	file_community_proto_goTypes = nil
	file_community_proto_depIdxs = nil
}
