// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: media.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Mimetype      string                 `protobuf:"bytes,3,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	ArchiveId     string                 `protobuf:"bytes,5,opt,name=archive_id,proto3" json:"archive_id,omitempty"`
	TorrentId     string                 `protobuf:"bytes,6,opt,name=torrent_id,proto3" json:"torrent_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	KnownMediaId  string                 `protobuf:"bytes,9,opt,name=known_media_id,proto3" json:"known_media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Media) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Media) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *Media) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Media) GetArchiveId() string {
	if x != nil {
		return x.ArchiveId
	}
	return ""
}

func (x *Media) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

func (x *Media) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Media) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Media) GetKnownMediaId() string {
	if x != nil {
		return x.KnownMediaId
	}
	return ""
}

type MediaSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Mimetypes     []string               `protobuf:"bytes,2,rep,name=mimetypes,proto3" json:"mimetypes,omitempty"`
	Offset        uint64                 `protobuf:"varint,900,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,901,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaSearchRequest) Reset() {
	*x = MediaSearchRequest{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSearchRequest) ProtoMessage() {}

func (x *MediaSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSearchRequest.ProtoReflect.Descriptor instead.
func (*MediaSearchRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *MediaSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *MediaSearchRequest) GetMimetypes() []string {
	if x != nil {
		return x.Mimetypes
	}
	return nil
}

func (x *MediaSearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *MediaSearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type MediaSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          *MediaSearchRequest    `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Media               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaSearchResponse) Reset() {
	*x = MediaSearchResponse{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSearchResponse) ProtoMessage() {}

func (x *MediaSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSearchResponse.ProtoReflect.Descriptor instead.
func (*MediaSearchResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *MediaSearchResponse) GetNext() *MediaSearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *MediaSearchResponse) GetItems() []*Media {
	if x != nil {
		return x.Items
	}
	return nil
}

type MediaUpdateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUpdateRequest) Reset() {
	*x = MediaUpdateRequest{}
	mi := &file_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUpdateRequest) ProtoMessage() {}

func (x *MediaUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUpdateRequest.ProtoReflect.Descriptor instead.
func (*MediaUpdateRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{3}
}

func (x *MediaUpdateRequest) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediaUpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUpdateResponse) Reset() {
	*x = MediaUpdateResponse{}
	mi := &file_media_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUpdateResponse) ProtoMessage() {}

func (x *MediaUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUpdateResponse.ProtoReflect.Descriptor instead.
func (*MediaUpdateResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{4}
}

func (x *MediaUpdateResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediaDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaDeleteRequest) Reset() {
	*x = MediaDeleteRequest{}
	mi := &file_media_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaDeleteRequest) ProtoMessage() {}

func (x *MediaDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaDeleteRequest.ProtoReflect.Descriptor instead.
func (*MediaDeleteRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{5}
}

type MediaDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaDeleteResponse) Reset() {
	*x = MediaDeleteResponse{}
	mi := &file_media_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaDeleteResponse) ProtoMessage() {}

func (x *MediaDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaDeleteResponse.ProtoReflect.Descriptor instead.
func (*MediaDeleteResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{6}
}

func (x *MediaDeleteResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediaUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaUploadResponse) Reset() {
	*x = MediaUploadResponse{}
	mi := &file_media_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaUploadResponse) ProtoMessage() {}

func (x *MediaUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaUploadResponse.ProtoReflect.Descriptor instead.
func (*MediaUploadResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{7}
}

func (x *MediaUploadResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

type Download struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Bytes         uint64                 `protobuf:"varint,2,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Downloaded    uint64                 `protobuf:"varint,3,opt,name=downloaded,proto3" json:"downloaded,omitempty"`
	InitiatedAt   string                 `protobuf:"bytes,4,opt,name=initiated_at,proto3" json:"initiated_at,omitempty"`
	PausedAt      string                 `protobuf:"bytes,5,opt,name=paused_at,proto3" json:"paused_at,omitempty"`
	Peers         uint32                 `protobuf:"varint,6,opt,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Download) Reset() {
	*x = Download{}
	mi := &file_media_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Download) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Download) ProtoMessage() {}

func (x *Download) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Download.ProtoReflect.Descriptor instead.
func (*Download) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{8}
}

func (x *Download) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Download) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Download) GetDownloaded() uint64 {
	if x != nil {
		return x.Downloaded
	}
	return 0
}

func (x *Download) GetInitiatedAt() string {
	if x != nil {
		return x.InitiatedAt
	}
	return ""
}

func (x *Download) GetPausedAt() string {
	if x != nil {
		return x.PausedAt
	}
	return ""
}

func (x *Download) GetPeers() uint32 {
	if x != nil {
		return x.Peers
	}
	return 0
}

type MagnetCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MagnetCreateRequest) Reset() {
	*x = MagnetCreateRequest{}
	mi := &file_media_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MagnetCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagnetCreateRequest) ProtoMessage() {}

func (x *MagnetCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagnetCreateRequest.ProtoReflect.Descriptor instead.
func (*MagnetCreateRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{9}
}

func (x *MagnetCreateRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type MagnetCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Download      *Download              `protobuf:"bytes,1,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MagnetCreateResponse) Reset() {
	*x = MagnetCreateResponse{}
	mi := &file_media_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MagnetCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MagnetCreateResponse) ProtoMessage() {}

func (x *MagnetCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MagnetCreateResponse.ProtoReflect.Descriptor instead.
func (*MagnetCreateResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{10}
}

func (x *MagnetCreateResponse) GetDownload() *Download {
	if x != nil {
		return x.Download
	}
	return nil
}

type DownloadSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Mimetypes     []string               `protobuf:"bytes,2,rep,name=mimetypes,proto3" json:"mimetypes,omitempty"`
	Completed     bool                   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	Offset        uint64                 `protobuf:"varint,900,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,901,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSearchRequest) Reset() {
	*x = DownloadSearchRequest{}
	mi := &file_media_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSearchRequest) ProtoMessage() {}

func (x *DownloadSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSearchRequest.ProtoReflect.Descriptor instead.
func (*DownloadSearchRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{11}
}

func (x *DownloadSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *DownloadSearchRequest) GetMimetypes() []string {
	if x != nil {
		return x.Mimetypes
	}
	return nil
}

func (x *DownloadSearchRequest) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *DownloadSearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *DownloadSearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type DownloadSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          *DownloadSearchRequest `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Download            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadSearchResponse) Reset() {
	*x = DownloadSearchResponse{}
	mi := &file_media_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadSearchResponse) ProtoMessage() {}

func (x *DownloadSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadSearchResponse.ProtoReflect.Descriptor instead.
func (*DownloadSearchResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{12}
}

func (x *DownloadSearchResponse) GetNext() *DownloadSearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *DownloadSearchResponse) GetItems() []*Download {
	if x != nil {
		return x.Items
	}
	return nil
}

type DownloadMetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadMetadataRequest) Reset() {
	*x = DownloadMetadataRequest{}
	mi := &file_media_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMetadataRequest) ProtoMessage() {}

func (x *DownloadMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMetadataRequest.ProtoReflect.Descriptor instead.
func (*DownloadMetadataRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{13}
}

type DownloadMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Download      *Download              `protobuf:"bytes,1,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadMetadataResponse) Reset() {
	*x = DownloadMetadataResponse{}
	mi := &file_media_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadMetadataResponse) ProtoMessage() {}

func (x *DownloadMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadMetadataResponse.ProtoReflect.Descriptor instead.
func (*DownloadMetadataResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{14}
}

func (x *DownloadMetadataResponse) GetDownload() *Download {
	if x != nil {
		return x.Download
	}
	return nil
}

type DownloadBeginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBeginRequest) Reset() {
	*x = DownloadBeginRequest{}
	mi := &file_media_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBeginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBeginRequest) ProtoMessage() {}

func (x *DownloadBeginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBeginRequest.ProtoReflect.Descriptor instead.
func (*DownloadBeginRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{15}
}

type DownloadBeginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Download      *Download              `protobuf:"bytes,1,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadBeginResponse) Reset() {
	*x = DownloadBeginResponse{}
	mi := &file_media_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadBeginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadBeginResponse) ProtoMessage() {}

func (x *DownloadBeginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadBeginResponse.ProtoReflect.Descriptor instead.
func (*DownloadBeginResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{16}
}

func (x *DownloadBeginResponse) GetDownload() *Download {
	if x != nil {
		return x.Download
	}
	return nil
}

type DownloadPauseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPauseRequest) Reset() {
	*x = DownloadPauseRequest{}
	mi := &file_media_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPauseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPauseRequest) ProtoMessage() {}

func (x *DownloadPauseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPauseRequest.ProtoReflect.Descriptor instead.
func (*DownloadPauseRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{17}
}

type DownloadPauseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Download      *Download              `protobuf:"bytes,1,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadPauseResponse) Reset() {
	*x = DownloadPauseResponse{}
	mi := &file_media_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadPauseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadPauseResponse) ProtoMessage() {}

func (x *DownloadPauseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadPauseResponse.ProtoReflect.Descriptor instead.
func (*DownloadPauseResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{18}
}

func (x *DownloadPauseResponse) GetDownload() *Download {
	if x != nil {
		return x.Download
	}
	return nil
}

type Published struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mimetype      string                 `protobuf:"bytes,2,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Bytes         uint64                 `protobuf:"varint,4,opt,name=bytes,proto3" json:"bytes,omitempty"`
	Entropy       string                 `protobuf:"bytes,5,opt,name=entropy,proto3" json:"entropy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Published) Reset() {
	*x = Published{}
	mi := &file_media_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Published) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Published) ProtoMessage() {}

func (x *Published) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Published.ProtoReflect.Descriptor instead.
func (*Published) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{19}
}

func (x *Published) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Published) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *Published) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Published) GetBytes() uint64 {
	if x != nil {
		return x.Bytes
	}
	return 0
}

func (x *Published) GetEntropy() string {
	if x != nil {
		return x.Entropy
	}
	return ""
}

type PublishedUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entropy       string                 `protobuf:"bytes,1,opt,name=entropy,proto3" json:"entropy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedUploadRequest) Reset() {
	*x = PublishedUploadRequest{}
	mi := &file_media_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedUploadRequest) ProtoMessage() {}

func (x *PublishedUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedUploadRequest.ProtoReflect.Descriptor instead.
func (*PublishedUploadRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{20}
}

func (x *PublishedUploadRequest) GetEntropy() string {
	if x != nil {
		return x.Entropy
	}
	return ""
}

type PublishedUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Published     *Published             `protobuf:"bytes,1,opt,name=published,proto3" json:"published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedUploadResponse) Reset() {
	*x = PublishedUploadResponse{}
	mi := &file_media_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedUploadResponse) ProtoMessage() {}

func (x *PublishedUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedUploadResponse.ProtoReflect.Descriptor instead.
func (*PublishedUploadResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{21}
}

func (x *PublishedUploadResponse) GetPublished() *Published {
	if x != nil {
		return x.Published
	}
	return nil
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\x05media\"\x93\x02\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bmimetype\x18\x03 \x01(\tR\bmimetype\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x1e\n" +
	"\n" +
	"archive_id\x18\x05 \x01(\tR\n" +
	"archive_id\x12\x1e\n" +
	"\n" +
	"torrent_id\x18\x06 \x01(\tR\n" +
	"torrent_id\x12\x1e\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\n" +
	"created_at\x12\x1e\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\n" +
	"updated_at\x12&\n" +
	"\x0eknown_media_id\x18\t \x01(\tR\x0eknown_media_id\"\x87\x01\n" +
	"\x12MediaSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1c\n" +
	"\tmimetypes\x18\x02 \x03(\tR\tmimetypes\x12\x17\n" +
	"\x06offset\x18\x84\a \x01(\x04R\x06offset\x12\x15\n" +
	"\x05limit\x18\x85\a \x01(\x04R\x05limitJ\x05\b\x03\x10\x84\aJ\x06\b\x86\a\x10\xe8\a\"h\n" +
	"\x13MediaSearchResponse\x12-\n" +
	"\x04next\x18\x01 \x01(\v2\x19.media.MediaSearchRequestR\x04next\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.media.MediaR\x05items\"8\n" +
	"\x12MediaUpdateRequest\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\"9\n" +
	"\x13MediaUpdateResponse\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\"\x14\n" +
	"\x12MediaDeleteRequest\"9\n" +
	"\x13MediaDeleteResponse\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\"9\n" +
	"\x13MediaUploadResponse\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\"\xbc\x01\n" +
	"\bDownload\x12\"\n" +
	"\x05media\x18\x01 \x01(\v2\f.media.MediaR\x05media\x12\x14\n" +
	"\x05bytes\x18\x02 \x01(\x04R\x05bytes\x12\x1e\n" +
	"\n" +
	"downloaded\x18\x03 \x01(\x04R\n" +
	"downloaded\x12\"\n" +
	"\finitiated_at\x18\x04 \x01(\tR\finitiated_at\x12\x1c\n" +
	"\tpaused_at\x18\x05 \x01(\tR\tpaused_at\x12\x14\n" +
	"\x05peers\x18\x06 \x01(\rR\x05peers\"'\n" +
	"\x13MagnetCreateRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"C\n" +
	"\x14MagnetCreateResponse\x12+\n" +
	"\bdownload\x18\x01 \x01(\v2\x0f.media.DownloadR\bdownload\"\xa8\x01\n" +
	"\x15DownloadSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1c\n" +
	"\tmimetypes\x18\x02 \x03(\tR\tmimetypes\x12\x1c\n" +
	"\tcompleted\x18\x03 \x01(\bR\tcompleted\x12\x17\n" +
	"\x06offset\x18\x84\a \x01(\x04R\x06offset\x12\x15\n" +
	"\x05limit\x18\x85\a \x01(\x04R\x05limitJ\x05\b\x04\x10\x84\aJ\x06\b\x86\a\x10\xe8\a\"q\n" +
	"\x16DownloadSearchResponse\x120\n" +
	"\x04next\x18\x01 \x01(\v2\x1c.media.DownloadSearchRequestR\x04next\x12%\n" +
	"\x05items\x18\x02 \x03(\v2\x0f.media.DownloadR\x05items\"\x19\n" +
	"\x17DownloadMetadataRequest\"G\n" +
	"\x18DownloadMetadataResponse\x12+\n" +
	"\bdownload\x18\x01 \x01(\v2\x0f.media.DownloadR\bdownload\"\x16\n" +
	"\x14DownloadBeginRequest\"D\n" +
	"\x15DownloadBeginResponse\x12+\n" +
	"\bdownload\x18\x01 \x01(\v2\x0f.media.DownloadR\bdownload\"\x16\n" +
	"\x14DownloadPauseRequest\"D\n" +
	"\x15DownloadPauseResponse\x12+\n" +
	"\bdownload\x18\x01 \x01(\v2\x0f.media.DownloadR\bdownload\"\x89\x01\n" +
	"\tPublished\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bmimetype\x18\x02 \x01(\tR\bmimetype\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05bytes\x18\x04 \x01(\x04R\x05bytes\x12\x18\n" +
	"\aentropy\x18\x05 \x01(\tR\aentropy\"2\n" +
	"\x16PublishedUploadRequest\x12\x18\n" +
	"\aentropy\x18\x01 \x01(\tR\aentropy\"I\n" +
	"\x17PublishedUploadResponse\x12.\n" +
	"\tpublished\x18\x01 \x01(\v2\x10.media.PublishedR\tpublishedb\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_media_proto_goTypes = []any{
	(*Media)(nil),                    // 0: media.Media
	(*MediaSearchRequest)(nil),       // 1: media.MediaSearchRequest
	(*MediaSearchResponse)(nil),      // 2: media.MediaSearchResponse
	(*MediaUpdateRequest)(nil),       // 3: media.MediaUpdateRequest
	(*MediaUpdateResponse)(nil),      // 4: media.MediaUpdateResponse
	(*MediaDeleteRequest)(nil),       // 5: media.MediaDeleteRequest
	(*MediaDeleteResponse)(nil),      // 6: media.MediaDeleteResponse
	(*MediaUploadResponse)(nil),      // 7: media.MediaUploadResponse
	(*Download)(nil),                 // 8: media.Download
	(*MagnetCreateRequest)(nil),      // 9: media.MagnetCreateRequest
	(*MagnetCreateResponse)(nil),     // 10: media.MagnetCreateResponse
	(*DownloadSearchRequest)(nil),    // 11: media.DownloadSearchRequest
	(*DownloadSearchResponse)(nil),   // 12: media.DownloadSearchResponse
	(*DownloadMetadataRequest)(nil),  // 13: media.DownloadMetadataRequest
	(*DownloadMetadataResponse)(nil), // 14: media.DownloadMetadataResponse
	(*DownloadBeginRequest)(nil),     // 15: media.DownloadBeginRequest
	(*DownloadBeginResponse)(nil),    // 16: media.DownloadBeginResponse
	(*DownloadPauseRequest)(nil),     // 17: media.DownloadPauseRequest
	(*DownloadPauseResponse)(nil),    // 18: media.DownloadPauseResponse
	(*Published)(nil),                // 19: media.Published
	(*PublishedUploadRequest)(nil),   // 20: media.PublishedUploadRequest
	(*PublishedUploadResponse)(nil),  // 21: media.PublishedUploadResponse
}
var file_media_proto_depIdxs = []int32{
	1,  // 0: media.MediaSearchResponse.next:type_name -> media.MediaSearchRequest
	0,  // 1: media.MediaSearchResponse.items:type_name -> media.Media
	0,  // 2: media.MediaUpdateRequest.media:type_name -> media.Media
	0,  // 3: media.MediaUpdateResponse.media:type_name -> media.Media
	0,  // 4: media.MediaDeleteResponse.media:type_name -> media.Media
	0,  // 5: media.MediaUploadResponse.media:type_name -> media.Media
	0,  // 6: media.Download.media:type_name -> media.Media
	8,  // 7: media.MagnetCreateResponse.download:type_name -> media.Download
	11, // 8: media.DownloadSearchResponse.next:type_name -> media.DownloadSearchRequest
	8,  // 9: media.DownloadSearchResponse.items:type_name -> media.Download
	8,  // 10: media.DownloadMetadataResponse.download:type_name -> media.Download
	8,  // 11: media.DownloadBeginResponse.download:type_name -> media.Download
	8,  // 12: media.DownloadPauseResponse.download:type_name -> media.Download
	19, // 13: media.PublishedUploadResponse.published:type_name -> media.Published
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
