// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: media.known.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Known struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Mimetype      string                 `protobuf:"bytes,3,opt,name=mimetype,proto3" json:"mimetype,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	ArchiveId     string                 `protobuf:"bytes,5,opt,name=archive_id,proto3" json:"archive_id,omitempty"`
	TorrentId     string                 `protobuf:"bytes,6,opt,name=torrent_id,proto3" json:"torrent_id,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,8,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	Metadata      string                 `protobuf:"bytes,9,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Known) Reset() {
	*x = Known{}
	mi := &file_media_known_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Known) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Known) ProtoMessage() {}

func (x *Known) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Known.ProtoReflect.Descriptor instead.
func (*Known) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{0}
}

func (x *Known) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Known) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Known) GetMimetype() string {
	if x != nil {
		return x.Mimetype
	}
	return ""
}

func (x *Known) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Known) GetArchiveId() string {
	if x != nil {
		return x.ArchiveId
	}
	return ""
}

func (x *Known) GetTorrentId() string {
	if x != nil {
		return x.TorrentId
	}
	return ""
}

func (x *Known) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Known) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Known) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type KnownSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Offset        uint64                 `protobuf:"varint,900,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,901,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownSearchRequest) Reset() {
	*x = KnownSearchRequest{}
	mi := &file_media_known_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownSearchRequest) ProtoMessage() {}

func (x *KnownSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownSearchRequest.ProtoReflect.Descriptor instead.
func (*KnownSearchRequest) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{1}
}

func (x *KnownSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *KnownSearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *KnownSearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type KnownSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Next          *KnownSearchRequest    `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Known               `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownSearchResponse) Reset() {
	*x = KnownSearchResponse{}
	mi := &file_media_known_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownSearchResponse) ProtoMessage() {}

func (x *KnownSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownSearchResponse.ProtoReflect.Descriptor instead.
func (*KnownSearchResponse) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{2}
}

func (x *KnownSearchResponse) GetNext() *KnownSearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *KnownSearchResponse) GetItems() []*Known {
	if x != nil {
		return x.Items
	}
	return nil
}

type KnownMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownMatchRequest) Reset() {
	*x = KnownMatchRequest{}
	mi := &file_media_known_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownMatchRequest) ProtoMessage() {}

func (x *KnownMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownMatchRequest.ProtoReflect.Descriptor instead.
func (*KnownMatchRequest) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{3}
}

func (x *KnownMatchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type KnownLookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownLookupRequest) Reset() {
	*x = KnownLookupRequest{}
	mi := &file_media_known_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownLookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownLookupRequest) ProtoMessage() {}

func (x *KnownLookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownLookupRequest.ProtoReflect.Descriptor instead.
func (*KnownLookupRequest) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{4}
}

type KnownLookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Known         *Known                 `protobuf:"bytes,1,opt,name=known,proto3" json:"known,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnownLookupResponse) Reset() {
	*x = KnownLookupResponse{}
	mi := &file_media_known_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnownLookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnownLookupResponse) ProtoMessage() {}

func (x *KnownLookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_known_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnownLookupResponse.ProtoReflect.Descriptor instead.
func (*KnownLookupResponse) Descriptor() ([]byte, []int) {
	return file_media_known_proto_rawDescGZIP(), []int{5}
}

func (x *KnownLookupResponse) GetKnown() *Known {
	if x != nil {
		return x.Known
	}
	return nil
}

var File_media_known_proto protoreflect.FileDescriptor

const file_media_known_proto_rawDesc = "" +
	"\n" +
	"\x11media.known.proto\x12\x05media\"\x87\x02\n" +
	"\x05Known\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bmimetype\x18\x03 \x01(\tR\bmimetype\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x1e\n" +
	"\n" +
	"archive_id\x18\x05 \x01(\tR\n" +
	"archive_id\x12\x1e\n" +
	"\n" +
	"torrent_id\x18\x06 \x01(\tR\n" +
	"torrent_id\x12\x1e\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\n" +
	"created_at\x12\x1e\n" +
	"\n" +
	"updated_at\x18\b \x01(\tR\n" +
	"updated_at\x12\x1a\n" +
	"\bmetadata\x18\t \x01(\tR\bmetadata\"i\n" +
	"\x12KnownSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\x06offset\x18\x84\a \x01(\x04R\x06offset\x12\x15\n" +
	"\x05limit\x18\x85\a \x01(\x04R\x05limitJ\x05\b\x02\x10\x84\aJ\x06\b\x86\a\x10\xe8\a\"h\n" +
	"\x13KnownSearchResponse\x12-\n" +
	"\x04next\x18\x01 \x01(\v2\x19.media.KnownSearchRequestR\x04next\x12\"\n" +
	"\x05items\x18\x02 \x03(\v2\f.media.KnownR\x05items\")\n" +
	"\x11KnownMatchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\"\x14\n" +
	"\x12KnownLookupRequest\"9\n" +
	"\x13KnownLookupResponse\x12\"\n" +
	"\x05known\x18\x01 \x01(\v2\f.media.KnownR\x05knownb\x06proto3"

var (
	file_media_known_proto_rawDescOnce sync.Once
	file_media_known_proto_rawDescData []byte
)

func file_media_known_proto_rawDescGZIP() []byte {
	file_media_known_proto_rawDescOnce.Do(func() {
		file_media_known_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_known_proto_rawDesc), len(file_media_known_proto_rawDesc)))
	})
	return file_media_known_proto_rawDescData
}

var file_media_known_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_media_known_proto_goTypes = []any{
	(*Known)(nil),               // 0: media.Known
	(*KnownSearchRequest)(nil),  // 1: media.KnownSearchRequest
	(*KnownSearchResponse)(nil), // 2: media.KnownSearchResponse
	(*KnownMatchRequest)(nil),   // 3: media.KnownMatchRequest
	(*KnownLookupRequest)(nil),  // 4: media.KnownLookupRequest
	(*KnownLookupResponse)(nil), // 5: media.KnownLookupResponse
}
var file_media_known_proto_depIdxs = []int32{
	1, // 0: media.KnownSearchResponse.next:type_name -> media.KnownSearchRequest
	0, // 1: media.KnownSearchResponse.items:type_name -> media.Known
	0, // 2: media.KnownLookupResponse.known:type_name -> media.Known
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_media_known_proto_init() }
func file_media_known_proto_init() {
	if File_media_known_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_known_proto_rawDesc), len(file_media_known_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_known_proto_goTypes,
		DependencyIndexes: file_media_known_proto_depIdxs,
		MessageInfos:      file_media_known_proto_msgTypes,
	}.Build()
	File_media_known_proto = out.File
	file_media_known_proto_goTypes = nil
	file_media_known_proto_depIdxs = nil
}
