// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: meta.wireguard.proto

package metaapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wireguard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wireguard) Reset() {
	*x = Wireguard{}
	mi := &file_meta_wireguard_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wireguard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wireguard) ProtoMessage() {}

func (x *Wireguard) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wireguard.ProtoReflect.Descriptor instead.
func (*Wireguard) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{0}
}

func (x *Wireguard) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type WireguardSearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit         uint64                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Status        uint32                 `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireguardSearchRequest) Reset() {
	*x = WireguardSearchRequest{}
	mi := &file_meta_wireguard_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardSearchRequest) ProtoMessage() {}

func (x *WireguardSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardSearchRequest.ProtoReflect.Descriptor instead.
func (*WireguardSearchRequest) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{1}
}

func (x *WireguardSearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *WireguardSearchRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *WireguardSearchRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *WireguardSearchRequest) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type WireguardSearchResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Next          *WireguardSearchRequest `protobuf:"bytes,1,opt,name=next,proto3" json:"next,omitempty"`
	Items         []*Wireguard            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireguardSearchResponse) Reset() {
	*x = WireguardSearchResponse{}
	mi := &file_meta_wireguard_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardSearchResponse) ProtoMessage() {}

func (x *WireguardSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardSearchResponse.ProtoReflect.Descriptor instead.
func (*WireguardSearchResponse) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{2}
}

func (x *WireguardSearchResponse) GetNext() *WireguardSearchRequest {
	if x != nil {
		return x.Next
	}
	return nil
}

func (x *WireguardSearchResponse) GetItems() []*Wireguard {
	if x != nil {
		return x.Items
	}
	return nil
}

type WireguardTouchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireguardTouchRequest) Reset() {
	*x = WireguardTouchRequest{}
	mi := &file_meta_wireguard_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardTouchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardTouchRequest) ProtoMessage() {}

func (x *WireguardTouchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardTouchRequest.ProtoReflect.Descriptor instead.
func (*WireguardTouchRequest) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{3}
}

type WireguardTouchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireguardTouchResponse) Reset() {
	*x = WireguardTouchResponse{}
	mi := &file_meta_wireguard_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardTouchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardTouchResponse) ProtoMessage() {}

func (x *WireguardTouchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardTouchResponse.ProtoReflect.Descriptor instead.
func (*WireguardTouchResponse) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{4}
}

type WireguardUploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireguardUploadRequest) Reset() {
	*x = WireguardUploadRequest{}
	mi := &file_meta_wireguard_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardUploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardUploadRequest) ProtoMessage() {}

func (x *WireguardUploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardUploadRequest.ProtoReflect.Descriptor instead.
func (*WireguardUploadRequest) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{5}
}

type WireguardUploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wireguard     *Wireguard             `protobuf:"bytes,1,opt,name=Wireguard,json=wireguard,proto3" json:"Wireguard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireguardUploadResponse) Reset() {
	*x = WireguardUploadResponse{}
	mi := &file_meta_wireguard_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardUploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardUploadResponse) ProtoMessage() {}

func (x *WireguardUploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardUploadResponse.ProtoReflect.Descriptor instead.
func (*WireguardUploadResponse) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{6}
}

func (x *WireguardUploadResponse) GetWireguard() *Wireguard {
	if x != nil {
		return x.Wireguard
	}
	return nil
}

type WireguardCurrentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireguardCurrentRequest) Reset() {
	*x = WireguardCurrentRequest{}
	mi := &file_meta_wireguard_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardCurrentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardCurrentRequest) ProtoMessage() {}

func (x *WireguardCurrentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardCurrentRequest.ProtoReflect.Descriptor instead.
func (*WireguardCurrentRequest) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{7}
}

type WireguardCurrentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wireguard     *Wireguard             `protobuf:"bytes,1,opt,name=Wireguard,json=wireguard,proto3" json:"Wireguard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireguardCurrentResponse) Reset() {
	*x = WireguardCurrentResponse{}
	mi := &file_meta_wireguard_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardCurrentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardCurrentResponse) ProtoMessage() {}

func (x *WireguardCurrentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardCurrentResponse.ProtoReflect.Descriptor instead.
func (*WireguardCurrentResponse) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{8}
}

func (x *WireguardCurrentResponse) GetWireguard() *Wireguard {
	if x != nil {
		return x.Wireguard
	}
	return nil
}

type WireguardDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireguardDeleteRequest) Reset() {
	*x = WireguardDeleteRequest{}
	mi := &file_meta_wireguard_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardDeleteRequest) ProtoMessage() {}

func (x *WireguardDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardDeleteRequest.ProtoReflect.Descriptor instead.
func (*WireguardDeleteRequest) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{9}
}

type WireguardDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wireguard     *Wireguard             `protobuf:"bytes,1,opt,name=Wireguard,json=wireguard,proto3" json:"Wireguard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WireguardDeleteResponse) Reset() {
	*x = WireguardDeleteResponse{}
	mi := &file_meta_wireguard_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireguardDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireguardDeleteResponse) ProtoMessage() {}

func (x *WireguardDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meta_wireguard_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireguardDeleteResponse.ProtoReflect.Descriptor instead.
func (*WireguardDeleteResponse) Descriptor() ([]byte, []int) {
	return file_meta_wireguard_proto_rawDescGZIP(), []int{10}
}

func (x *WireguardDeleteResponse) GetWireguard() *Wireguard {
	if x != nil {
		return x.Wireguard
	}
	return nil
}

var File_meta_wireguard_proto protoreflect.FileDescriptor

const file_meta_wireguard_proto_rawDesc = "" +
	"\n" +
	"\x14meta.wireguard.proto\x12\x04meta\"\x1b\n" +
	"\tWireguard\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"t\n" +
	"\x16WireguardSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x04R\x05limit\x12\x16\n" +
	"\x06status\x18\x04 \x01(\rR\x06status\"r\n" +
	"\x17WireguardSearchResponse\x120\n" +
	"\x04next\x18\x01 \x01(\v2\x1c.meta.WireguardSearchRequestR\x04next\x12%\n" +
	"\x05items\x18\x02 \x03(\v2\x0f.meta.WireguardR\x05items\"\x17\n" +
	"\x15WireguardTouchRequest\"\x18\n" +
	"\x16WireguardTouchResponse\"\x18\n" +
	"\x16WireguardUploadRequest\"H\n" +
	"\x17WireguardUploadResponse\x12-\n" +
	"\tWireguard\x18\x01 \x01(\v2\x0f.meta.WireguardR\twireguard\"\x19\n" +
	"\x17WireguardCurrentRequest\"I\n" +
	"\x18WireguardCurrentResponse\x12-\n" +
	"\tWireguard\x18\x01 \x01(\v2\x0f.meta.WireguardR\twireguard\"\x18\n" +
	"\x16WireguardDeleteRequest\"H\n" +
	"\x17WireguardDeleteResponse\x12-\n" +
	"\tWireguard\x18\x01 \x01(\v2\x0f.meta.WireguardR\twireguardb\x06proto3"

var (
	file_meta_wireguard_proto_rawDescOnce sync.Once
	file_meta_wireguard_proto_rawDescData []byte
)

func file_meta_wireguard_proto_rawDescGZIP() []byte {
	file_meta_wireguard_proto_rawDescOnce.Do(func() {
		file_meta_wireguard_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meta_wireguard_proto_rawDesc), len(file_meta_wireguard_proto_rawDesc)))
	})
	return file_meta_wireguard_proto_rawDescData
}

var file_meta_wireguard_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_meta_wireguard_proto_goTypes = []any{
	(*Wireguard)(nil),                // 0: meta.Wireguard
	(*WireguardSearchRequest)(nil),   // 1: meta.WireguardSearchRequest
	(*WireguardSearchResponse)(nil),  // 2: meta.WireguardSearchResponse
	(*WireguardTouchRequest)(nil),    // 3: meta.WireguardTouchRequest
	(*WireguardTouchResponse)(nil),   // 4: meta.WireguardTouchResponse
	(*WireguardUploadRequest)(nil),   // 5: meta.WireguardUploadRequest
	(*WireguardUploadResponse)(nil),  // 6: meta.WireguardUploadResponse
	(*WireguardCurrentRequest)(nil),  // 7: meta.WireguardCurrentRequest
	(*WireguardCurrentResponse)(nil), // 8: meta.WireguardCurrentResponse
	(*WireguardDeleteRequest)(nil),   // 9: meta.WireguardDeleteRequest
	(*WireguardDeleteResponse)(nil),  // 10: meta.WireguardDeleteResponse
}
var file_meta_wireguard_proto_depIdxs = []int32{
	1, // 0: meta.WireguardSearchResponse.next:type_name -> meta.WireguardSearchRequest
	0, // 1: meta.WireguardSearchResponse.items:type_name -> meta.Wireguard
	0, // 2: meta.WireguardUploadResponse.Wireguard:type_name -> meta.Wireguard
	0, // 3: meta.WireguardCurrentResponse.Wireguard:type_name -> meta.Wireguard
	0, // 4: meta.WireguardDeleteResponse.Wireguard:type_name -> meta.Wireguard
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_meta_wireguard_proto_init() }
func file_meta_wireguard_proto_init() {
	if File_meta_wireguard_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meta_wireguard_proto_rawDesc), len(file_meta_wireguard_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meta_wireguard_proto_goTypes,
		DependencyIndexes: file_meta_wireguard_proto_depIdxs,
		MessageInfos:      file_meta_wireguard_proto_msgTypes,
	}.Build()
	File_meta_wireguard_proto = out.File
	file_meta_wireguard_proto_goTypes = nil
	file_meta_wireguard_proto_depIdxs = nil
}
